### PR TITLE
Config File

### PR DESCRIPTION
**Pull request by mdamonconnolly**
This patch adds a config file.

The config file stores the constants data on disk so that it is persistent across multiple runs of the program. I've opted to not store the querys in the config since that's unrelated to configuration but I have moved the database path (and the other newly added paths) to the config file.

The config file not only contributes to solving issue #27 but also can be used in future for issues #26 #19 and #56 

I've also added pathlib as, from what I've found after searching, it's considered the more "correct" way of checking file existence rather than using os.

### CODE REVIEW

**Comment by JI511** [comment]
I removed the paths from config file. For Issue 27, what I meant by optional param was a path that could be passed in upon program start up, so for instance 'python Personal_Fitness.py -path my_path' if the user wanted to use a different DB. The log file will always be the same so no need for the path to be different. The backup_db folder will also always be the same so it can just be hard coded. The water option is a good example of what I was thinking of for a config file.

**Comment by JI511** [comment]
Also changed .cfg to .ini file type. Looks like online that is how configuration files are recognized.

**Comment by mdamonconnolly** [comment]
Thanks for the feedback!

re: creating a new .ini file if one did not slready exist, didn't it already do this at the top of the entry point in personal_fitness.py?

**Comment by JI511** [comment]
Yes, but I just moved the check into the read function so you don’t have to
call both init and read.

**Pull request merged**
