### PR TITLE
Pr/54 Updated branch

### PR DESCRIPTION
**Pull request by JI511**

### CODE REVIEW

**Comment by mdamonconnolly** [comment]
I'm not sure what I'm supposed to do, it says it has no conflict with base and therefore should work, so I just clicked "Approve changes",  as that all I need to do?

**Comment by JI511** [comment]
I just wanted you to look at what I changed on your branch to make sure you understood the reasoning behind everything. Specifically at commit 5. The no conflicts is referring to the 'master' branch that will contain these PR changes once merged. Hopefully that clears it up?

**Comment by mdamonconnolly** [comment]
Yep! I read your changes and am still studying the rest of the codebase too! It's a bit confusing trying to figure out what is being passed to db_api functions, but breaking it down line by line and putting print statements is helping me a little. Thanks for making the effort to help me learn! It's extremely valuable to me!

**Comment by JI511** [comment]
No problem, teaching is also a great way for me to learn. Programming can be very daunting but there is no other way to learn than by just doing it!

**Comment by mdamonconnolly** [comment]
Should the merged branches like this one be closed to prevent repo pollution?

**Comment by JI511** [comment]
Yes probably. I will try to start doing this.

**Pull request merged**
