### PR TITLE
table_to_csv patch

### PR DESCRIPTION
**Pull request by mdamonconnolly**
This patch adds the table_to_csv function.
Tested on weight_lifting, body_weight and morning_lifts. Calories gets ignored due to it being written to a separate text file.
Currently it writes to the src/. I didn't want to change that incase you want to do something specific with it.

### CODE REVIEW

**Comment by JI511** [comment]
Thank you for contributing!

**Comment by mdamonconnolly** [comment]
Thank you for merging! I'm still learning and this was very educational!

**Comment by JI511** [comment]
This is the best way to learn! May I ask how you found my repo?

**Comment by mdamonconnolly** [comment]
I was just looking through repo's on the "Explore" tab, and the way you've done your database is fascinating, Completely different to what i've seen before. You also use the issue tracker relentlessly which i really like. I've already picked up a ton of "best practises" from your code and also a bunch of "how the hell does this work???"  so this repo has been my focus!

**Pull request merged**
